#!/bin/bash

# Скрипт с инструкциями по настройке Cloudflare после установки Let's Encrypt
# Этот скрипт не выполняет автоматическую настройку (требуется ручное вмешательство),
# но предоставляет точные инструкции и проверки

echo "☁️  Настройка Cloudflare для работы с Let's Encrypt"
echo "=================================================="

# Получение текущего IP сервера
SERVER_IP=$(curl -s ifconfig.me)
DOMAIN="hawklets.com"

echo "📊 Текущая информация:"
echo "   Домен: $DOMAIN"
echo "   Сервер IP: $SERVER_IP"
echo ""

# Проверка DNS
echo "🔍 Проверка текущих DNS записей:"
echo "--------------------------------"
echo "   Запись A для $DOMAIN:"
dig +short $DOMAIN
echo ""
echo "   Запись A для www.$DOMAIN:"
dig +short www.$DOMAIN
echo ""

# Проверка SSL сертификата
echo "🔐 Проверка SSL сертификата на сервере:"
echo "--------------------------------------"
if [ -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]; then
    echo "✅ Let's Encrypt сертификат установлен"
    echo "   Путь: /etc/letsencrypt/live/$DOMAIN/"
    
    # Проверка даты истечения
    EXPIRY_DATE=$(openssl x509 -in "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" -noout -enddate 2>/dev/null | cut -d= -f2)
    if [ ! -z "$EXPIRY_DATE" ]; then
        echo "   Срок действия: $EXPIRY_DATE"
    fi
else
    echo "❌ Let's Encrypt сертификат НЕ найден"
    echo "   Сначала выполните установку Let's Encrypt"
fi
echo ""

# Проверка работы SSL локально
echo "🌐 Проверка работы SSL локально:"
echo "-------------------------------"
echo "   Проверка порта 443 на localhost:"
if timeout 5 curl -s -k https://localhost/api/health > /dev/null; then
    echo "   ✅ SSL работает локально"
else
    echo "   ❌ SSL НЕ работает локально"
    echo "   Проверьте: docker-compose -f /root/hawklets/docker-compose.prod.yml logs frontend"
fi
echo ""

echo "🎯 ИНСТРУКЦИИ ДЛЯ НАСТРОЙКИ CLOUDFLARE:"
echo "======================================"
echo ""
echo "1. 📱 ВОЙДИТЕ В CLOUDFLARE DASHBOARD"
echo "   URL: https://dash.cloudflare.com"
echo "   Выберите домен: $DOMAIN"
echo ""
echo "2. 🌐 ОБНОВИТЕ DNS ЗАПИСИ"
echo "   Перейдите: DNS → Records"
echo "   Найдите запись для $DOMAIN (тип A)"
echo "   Нажмите 'Edit' (карандаш)"
echo "   Установите:"
echo "   - Content/Value: $SERVER_IP"
echo "   - Proxy status: Proxied (оранжевое облако)"
echo "   - TTL: Auto"
echo "   Нажмите 'Save'"
echo ""
echo "3. 🔐 НАСТРОЙТЕ SSL/TLS"
echo "   Перейдите: SSL/TLS → Overview"
echo "   Установите:"
echo "   - SSL/TLS encryption mode: Full (strict)"
echo "   - Always Use HTTPS: On"
echo "   - Minimum TLS Version: TLS 1.2"
echo ""
echo "4. 🛡️ ПРОВЕРЬТЕ FIREWALL"
echo "   Перейдите: Security → WAF → Custom rules"
echo "   Убедитесь что нет правил блокирующих /api/*"
echo "   Если нужно, создайте правило:"
echo "   - Rule name: Allow API"
echo "   - Field: URI Path"
echo "   - Operator: contains"
echo "   - Value: /api"
echo "   - Action: Allow"
echo ""
echo "5. ⚡ ВКЛЮЧИТЕ УСКОРЕНИЕ (ОПЦИОНАЛЬНО)"
echo "   Перейдите: Speed → Optimization"
echo "   Рекомендуемые настройки:"
echo "   - Auto Minify: Включите для JS, CSS, HTML"
echo "   - Brotli: On"
echo ""
echo "6. 📊 ВКЛЮЧИТЕ АНАЛИТИКУ"
echo "   Перейдите: Analytics & Logs → Web Analytics"
echo "   Добавьте сайт для отслеживания трафика"
echo ""
echo "⏱️  ВРЕМЯ ОЖИДАНИЯ:"
echo "-----------------"
echo "После сохранения изменений:"
echo "- DNS изменения: 1-5 минут"
echo "- SSL изменения: 5-15 минут"
echo "- Полное распространение: до 30 минут"
echo ""
echo "🔍 ПРОВЕРКА ПОСЛЕ НАСТРОЙКИ:"
echo "---------------------------"
echo "Выполните эти команды после настройки Cloudflare:"
echo ""
echo "# 1. Проверка DNS (должен показывать Cloudflare IP, не ваш серверный IP)"
echo "dig +short $DOMAIN"
echo ""
echo "# 2. Проверка SSL сертификата через Cloudflare"
echo "openssl s_client -connect $DOMAIN:443 -servername $DOMAIN < /dev/null 2>/dev/null | openssl x509 -noout -subject -issuer"
echo ""
echo "# 3. Проверка API через Cloudflare"
echo "curl -v https://$DOMAIN/api/health"
echo ""
echo "# 4. Проверка заголовков Cloudflare"
echo "curl -s -I https://$DOMAIN | grep -i 'cf-ray\|server'"
echo ""
echo "✅ ОЖИДАЕМЫЕ РЕЗУЛЬТАТЫ:"
echo "-----------------------"
echo "1. DNS запись показывает Cloudflare IP (не $SERVER_IP)"
echo "2. SSL сертификат показывает 'Let's Encrypt' или 'Cloudflare'"
echo "3. API отвечает: {\"status\":\"healthy\",...}"
echo "4. Заголовки содержат 'cloudflare' или 'CF-Ray'"
echo ""
echo "🚨 УСТРАНЕНИЕ НЕПОЛАДОК:"
echo "----------------------"
echo ""
echo "Проблема: ERR_CONNECTION_REFUSED"
echo "Решение:"
echo "1. Проверьте что порт 443 открыт на сервере:"
echo "   sudo ufw status"
echo "   sudo ufw allow 443/tcp"
echo ""
echo "2. Проверьте что Docker контейнеры запущены:"
echo "   cd /root/hawklets"
echo "   docker-compose -f docker-compose.prod.yml ps"
echo ""
echo "3. Проверьте логи nginx:"
echo "   docker-compose -f docker-compose.prod.yml logs frontend"
echo ""
echo "Проблема: SSL certificate error"
echo "Решение:"
echo "1. Убедитесь что Cloudflare в режиме 'Full (strict)'"
echo "2. Проверьте что сертификат Let's Encrypt валиден:"
echo "   sudo certbot certificates"
echo ""
echo "Проблема: API работает но сайт не работает"
echo "Решение:"
echo "1. Проверьте что frontend контейнер запущен"
echo "2. Проверьте что nginx обслуживает статические файлы"
echo ""
echo "📞 ЕСЛИ ПРОБЛЕМА ОСТАЕТСЯ:"
echo "-------------------------"
echo "1. Временно отключите Cloudflare прокси:"
echo "   - В DNS записи измените на 'DNS only' (серое облако)"
echo "   - Проверьте работает ли API по HTTP: curl http://$DOMAIN/api/health"
echo ""
echo "2. Создайте поддомен для API:"
echo "   - Добавьте DNS запись: api.$DOMAIN → $SERVER_IP (DNS only)"
echo "   - Используйте https://api.$DOMAIN/api/health"
echo ""
echo "3. Обратитесь в поддержку Cloudflare"
echo ""
echo "📋 КОНТРОЛЬНЫЙ СПИСОК:"
echo "---------------------"
echo "[ ] DNS запись обновлена на $SERVER_IP"
echo "[ ] Proxy status: Proxied (оранжевое облако)"
echo "[ ] SSL режим: Full (strict)"
echo "[ ] Always Use HTTPS: On"
echo "[ ] Нет правил блокирующих /api/*"
echo "[ ] Подождал 30 минут после изменений"
echo "[ ] Проверил: curl https://$DOMAIN/api/health"
echo ""
echo "✨ ИНСТРУКЦИИ ЗАВЕРШЕНЫ!"
echo "Выполните шаги 1-6 в Cloudflare Dashboard, затем проверьте результат."